package Leisure;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Date;

import java.awt.Toolkit;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.Font;
import javax.swing.JPanel;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.JCheckBox;
import javax.swing.JButton;
import javax.swing.JComboBox;
import java.awt.GridBagLayout;
import java.awt.GridBagConstraints;
import java.awt.Insets;
import com.toedter.calendar.JDateChooser;
import com.toedter.components.JLocaleChooser;
import com.toedter.calendar.JDayChooser;
import com.toedter.calendar.demo.DateChooserPanel;

import java.awt.Checkbox;
import java.awt.Button;
import javax.swing.JRadioButton;
import java.awt.Label;
import javax.swing.JTextArea;
import javax.swing.JTabbedPane;


public class BookingPage extends javax.swing.JFrame {

		/**
		 * 
		 */
		private leisure_DB lDBBook = new leisure_DB();
		private static final long serialVersionUID = 1L;
		private String date; //= "YYYY-MM-DD";
		private String classBook; //= "Class";
		
		/**
		 * Creates new form leisureCentreProject
		 */
		public BookingPage() {
			initComponents();
			this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.png")));
		}

		
		public void setDate(String dateIn){
			date = dateIn;
			dateLabel.setText(date);
			
		}
		
		public void setClassType(String classID){
			classBook = classID;
			int cID = Integer.parseInt(classBook);
			
			classLabel.setText(lDBBook.getClassName(cID));
		}
		
		/**
		 * This method is called from within the constructor to initialise the form.
		 * WARNING: Do NOT modify this code. The content of this method is always
		 * regenerated by the Form Editor.
		 */
		//@SuppressWarnings("unchecked")
		// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
		private void initComponents() {

			
			
			Font tabFont = new Font("Tahoma",Font.BOLD|Font.ITALIC,18);
			
			jTabbedPane6 = new javax.swing.JTabbedPane();
			
			jTabbedPane6.setFont(tabFont);
			
			jTabbedPane1 = new javax.swing.JTabbedPane();
			
			jTabbedPane1.setFont(tabFont);
			
			
			
			setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

			
			GridBagLayout gridBagLayout = new GridBagLayout();
			gridBagLayout.columnWidths = new int[]{670, 0};
			gridBagLayout.rowHeights = new int[]{380, 0};
			gridBagLayout.columnWeights = new double[]{0.0, Double.MIN_VALUE};
			gridBagLayout.rowWeights = new double[]{0.0, Double.MIN_VALUE};
			getContentPane().setLayout(gridBagLayout);
			
			LeisureCentre = new javax.swing.JTabbedPane();
			
			LeisureCentre.setFont(new Font("Tahoma", Font.BOLD | Font.ITALIC, 22));
			GridBagConstraints gbc_LeisureCentre = new GridBagConstraints();
			gbc_LeisureCentre.fill = GridBagConstraints.BOTH;
			gbc_LeisureCentre.gridx = 0;
			gbc_LeisureCentre.gridy = 0;
			getContentPane().add(LeisureCentre, gbc_LeisureCentre);
			
			panel = new JPanel();
			LeisureCentre.addTab("Make Booking", null, panel, null);
			GridBagLayout gbl_panel = new GridBagLayout();
			gbl_panel.columnWidths = new int[]{0, 105, 0, 311, 0, 0, 0, 0};
			gbl_panel.rowHeights = new int[]{54, 0, 0, 0, 0, 0, 0, 0, 0};
			gbl_panel.columnWeights = new double[]{0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, Double.MIN_VALUE};
			gbl_panel.rowWeights = new double[]{0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, Double.MIN_VALUE};
			panel.setLayout(gbl_panel);
			
			lblNewLabel = new JLabel("Name");
			lblNewLabel.setFont(new Font("Tahoma", Font.BOLD, 20));
			GridBagConstraints gbc_lblNewLabel = new GridBagConstraints();
			gbc_lblNewLabel.anchor = GridBagConstraints.WEST;
			gbc_lblNewLabel.insets = new Insets(0, 0, 5, 5);
			gbc_lblNewLabel.gridx = 2;
			gbc_lblNewLabel.gridy = 2;
			panel.add(lblNewLabel, gbc_lblNewLabel);
			
			nameText = new JTextField();
			nameText.setFont(new Font("Tahoma", Font.PLAIN, 20));
			GridBagConstraints gbc_nameText = new GridBagConstraints();
			gbc_nameText.insets = new Insets(0, 0, 5, 5);
			gbc_nameText.fill = GridBagConstraints.HORIZONTAL;
			gbc_nameText.gridx = 3;
			gbc_nameText.gridy = 2;
			panel.add(nameText, gbc_nameText);
			nameText.setColumns(10);
			
			lblPhone = new JLabel("Phone#");
			lblPhone.setFont(new Font("Tahoma", Font.BOLD, 20));
			GridBagConstraints gbc_lblPhone = new GridBagConstraints();
			gbc_lblPhone.anchor = GridBagConstraints.WEST;
			gbc_lblPhone.insets = new Insets(0, 0, 5, 5);
			gbc_lblPhone.gridx = 2;
			gbc_lblPhone.gridy = 3;
			panel.add(lblPhone, gbc_lblPhone);
			
			phoneText = new JTextField();
			phoneText.setFont(new Font("Tahoma", Font.PLAIN, 20));
			GridBagConstraints gbc_phoneText = new GridBagConstraints();
			gbc_phoneText.insets = new Insets(0, 0, 5, 5);
			gbc_phoneText.fill = GridBagConstraints.HORIZONTAL;
			gbc_phoneText.gridx = 3;
			gbc_phoneText.gridy = 3;
			panel.add(phoneText, gbc_phoneText);
			phoneText.setColumns(10);
			
			lblMemberid = new JLabel("MemberID");
			lblMemberid.setFont(new Font("Tahoma", Font.BOLD, 20));
			GridBagConstraints gbc_lblMemberid = new GridBagConstraints();
			gbc_lblMemberid.anchor = GridBagConstraints.WEST;
			gbc_lblMemberid.insets = new Insets(0, 0, 5, 5);
			gbc_lblMemberid.gridx = 2;
			gbc_lblMemberid.gridy = 4;
			panel.add(lblMemberid, gbc_lblMemberid);
			
			memIDText = new JTextField();
			memIDText.setFont(new Font("Tahoma", Font.PLAIN, 20));
			memIDText.setText("Leave Unchanged if not Member");
			memIDText.setColumns(10);
			GridBagConstraints gbc_memIDText = new GridBagConstraints();
			gbc_memIDText.insets = new Insets(0, 0, 5, 5);
			gbc_memIDText.fill = GridBagConstraints.HORIZONTAL;
			gbc_memIDText.gridx = 3;
			gbc_memIDText.gridy = 4;
			panel.add(memIDText, gbc_memIDText);
			
			lblDateOfClass = new JLabel("Date of Class");
			lblDateOfClass.setFont(new Font("Tahoma", Font.BOLD, 20));
			GridBagConstraints gbc_lblDateOfClass = new GridBagConstraints();
			gbc_lblDateOfClass.anchor = GridBagConstraints.WEST;
			gbc_lblDateOfClass.insets = new Insets(0, 0, 5, 5);
			gbc_lblDateOfClass.gridx = 2;
			gbc_lblDateOfClass.gridy = 5;
			panel.add(lblDateOfClass, gbc_lblDateOfClass);
			
			dateLabel = new JLabel("YYYY-MM-DD");
			dateLabel.setFont(new Font("Tahoma", Font.PLAIN, 19));
			GridBagConstraints gbc_dateLabel = new GridBagConstraints();
			gbc_dateLabel.insets = new Insets(0, 0, 5, 5);
			gbc_dateLabel.gridx = 3;
			gbc_dateLabel.gridy = 5;
			panel.add(dateLabel, gbc_dateLabel);
			
			dateLabel.setText(date);
			
			
			
			
			lblClass = new JLabel("Class");
			lblClass.setFont(new Font("Tahoma", Font.BOLD, 20));
			GridBagConstraints gbc_lblClass = new GridBagConstraints();
			gbc_lblClass.anchor = GridBagConstraints.WEST;
			gbc_lblClass.insets = new Insets(0, 0, 5, 5);
			gbc_lblClass.gridx = 2;
			gbc_lblClass.gridy = 6;
			panel.add(lblClass, gbc_lblClass);
			
			classLabel = new JLabel("Class");
			classLabel.setFont(new Font("Tahoma", Font.PLAIN, 19));
			GridBagConstraints gbc_classLabel = new GridBagConstraints();
			gbc_classLabel.insets = new Insets(0, 0, 5, 5);
			gbc_classLabel.gridx = 3;
			gbc_classLabel.gridy = 6;
			panel.add(classLabel, gbc_classLabel);
			
			
			classLabel.setText(classBook);
			
			btnNewButton = new JButton("Confirm Booking");
			btnNewButton.setFont(new Font("Tahoma", Font.PLAIN, 20));
			GridBagConstraints gbc_btnNewButton = new GridBagConstraints();
			gbc_btnNewButton.anchor = GridBagConstraints.WEST;
			gbc_btnNewButton.insets = new Insets(0, 0, 0, 5);
			gbc_btnNewButton.gridx = 2;
			gbc_btnNewButton.gridy = 7;
			panel.add(btnNewButton, gbc_btnNewButton);
			
			
			
			btnNewButton.addActionListener(new ActionListener(){public void actionPerformed(ActionEvent confirmAE){
				
				//lDBBook.createCustomer(name, phone, cost, memID);
				String namet = nameText.getText();
				String phoneO = phoneText.getText();
				
				//cost needs to be pulled in; it isn't at the moment.
				int costId = 11;
				int memID = -1;
				
				if(memIDText.getText().equals("Leave Unchanged if not Member") || memIDText.getText().equals("")){
					memID = 0;
				}
				else{
					memID = Integer.parseInt(memIDText.getText());
				}
				
				lDBBook.createCustomer(namet, phoneO, costId, memID);
				int custid = lDBBook.getCustomerID(namet, phoneO, costId, memID);	
				
				try {
				    Thread.sleep(2000); 
				} catch (InterruptedException e) {
				    e.printStackTrace();
				}
				
				
				
				String date = dateLabel.getText();
				
				int classID = Integer.parseInt(classBook);
				
				lDBBook.createBooking(custid, date, classID);
				
				UIManager.put("OptionPane.messageFont", new Font("TimesNewRoman",Font.BOLD,20));
				UIManager.put("OptionPane.buttonFont", new Font("SansSerif",Font.BOLD,20));
				JOptionPane.showMessageDialog(null,"Booking is made","Thank You",JOptionPane.INFORMATION_MESSAGE);
				dispose();
			}
			});
			
			btnCancelBooking = new JButton("Cancel Booking");
			btnCancelBooking.setFont(new Font("Tahoma", Font.PLAIN, 20));
			GridBagConstraints gbc_btnCancelBooking = new GridBagConstraints();
			gbc_btnCancelBooking.anchor = GridBagConstraints.WEST;
			gbc_btnCancelBooking.insets = new Insets(0, 0, 0, 5);
			gbc_btnCancelBooking.gridx = 3;
			gbc_btnCancelBooking.gridy = 7;
			panel.add(btnCancelBooking, gbc_btnCancelBooking);

			
			btnCancelBooking.addActionListener(new ActionListener(){public void actionPerformed(ActionEvent confirmAE){
				
				dispose();
			
				}
			});
			
			
			LeisureCentre.getAccessibleContext().setAccessibleName("Booking");
			
			setDefaultCloseOperation(DISPOSE_ON_CLOSE);
			setResizable(false);
			pack();
		}// </editor-fold>//GEN-END:initComponents

		/**
		 * @param args the command line arguments
		 */
		public static void main(String args[]) {
			/* Set the Nimbus look and feel */
			//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
			/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
			 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
			 */
			try {
				for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
					if ("Nimbus".equals(info.getName())) {
						javax.swing.UIManager.setLookAndFeel(info.getClassName());
						break;
					}
				}
			} catch (ClassNotFoundException ex) {
				java.util.logging.Logger.getLogger(leisureCentreProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
			} catch (InstantiationException ex) {
				java.util.logging.Logger.getLogger(leisureCentreProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
			} catch (IllegalAccessException ex) {
				java.util.logging.Logger.getLogger(leisureCentreProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
			} catch (javax.swing.UnsupportedLookAndFeelException ex) {
				java.util.logging.Logger.getLogger(leisureCentreProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
			}
			//</editor-fold>

			/* Create and display the form */
			java.awt.EventQueue.invokeLater(new Runnable() {
				public void run() {
					BookingPage p = new BookingPage();
					p.setVisible(true);
					p.pack();
					p.setResizable(false);
					
				}
			});
		}

		// Variables declaration - do not modify//GEN-BEGIN:variables
		private javax.swing.JTabbedPane LeisureCentre;
		private javax.swing.JTabbedPane jTabbedPane1;
		private javax.swing.JTabbedPane jTabbedPane6;
		private JPanel panel;
		private JButton btnNewButton;
		private JLabel lblNewLabel;
		private JLabel lblPhone;
		private JTextField nameText;
		private JTextField phoneText;
		private JLabel lblMemberid;
		private JTextField memIDText;
		private JLabel lblDateOfClass;
		private JLabel lblClass;
		private JLabel classLabel;
		private JLabel dateLabel;
		private JButton btnCancelBooking;
	}
