package Leisure;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Date;

import java.awt.Toolkit;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.Font;
import javax.swing.JPanel;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.JCheckBox;
import javax.swing.JButton;
import javax.swing.JComboBox;
import java.awt.GridBagLayout;
import java.awt.GridBagConstraints;
import java.awt.Insets;
import com.toedter.calendar.JDateChooser;
import com.toedter.components.JLocaleChooser;
import com.toedter.calendar.JDayChooser;
import com.toedter.calendar.demo.DateChooserPanel;

import java.awt.Checkbox;
import java.awt.Button;
import javax.swing.JRadioButton;
import java.awt.Label;
import javax.swing.JTextArea;
import javax.swing.JTabbedPane;


public class CheckBooking extends javax.swing.JFrame {

		/**
		 * 
		 */
		private leisure_DB lDBBook = new leisure_DB();
		private static final long serialVersionUID = 1L;
		private String date; //= "YYYY-MM-DD";
		private String classBook; //= "Class";
		
		/**
		 * Creates new form leisureCentreProject
		 */
		public CheckBooking() {
			initComponents();
			this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.png")));
		}
		
		/**
		 * This method is called from within the constructor to initialise the form.
		 * WARNING: Do NOT modify this code. The content of this method is always
		 * regenerated by the Form Editor.
		 */
		//@SuppressWarnings("unchecked")
		// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
		private void initComponents() {

			
			
			Font tabFont = new Font("Tahoma",Font.BOLD|Font.ITALIC,18);
			
			jTabbedPane6 = new javax.swing.JTabbedPane();
			
			jTabbedPane6.setFont(tabFont);
			
			jTabbedPane1 = new javax.swing.JTabbedPane();
			
			jTabbedPane1.setFont(tabFont);
			
			
			
			setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

			
			GridBagLayout gridBagLayout = new GridBagLayout();
			gridBagLayout.columnWidths = new int[]{670, 0};
			gridBagLayout.rowHeights = new int[]{380, 0};
			gridBagLayout.columnWeights = new double[]{0.0, Double.MIN_VALUE};
			gridBagLayout.rowWeights = new double[]{0.0, Double.MIN_VALUE};
			getContentPane().setLayout(gridBagLayout);
			
			LeisureCentre = new javax.swing.JTabbedPane();
			
			LeisureCentre.setFont(new Font("Tahoma", Font.BOLD | Font.ITALIC, 22));
			GridBagConstraints gbc_LeisureCentre = new GridBagConstraints();
			gbc_LeisureCentre.fill = GridBagConstraints.BOTH;
			gbc_LeisureCentre.gridx = 0;
			gbc_LeisureCentre.gridy = 0;
			getContentPane().add(LeisureCentre, gbc_LeisureCentre);
			
			panel = new JPanel();
			LeisureCentre.addTab("Check Booking", null, panel, null);
			GridBagLayout gbl_panel = new GridBagLayout();
			gbl_panel.columnWidths = new int[]{0, 105, 0, 311, 0, 0, 0, 0};
			gbl_panel.rowHeights = new int[]{54, 0, 0, 0, 0, 0, 0, 0, 0};
			gbl_panel.columnWeights = new double[]{0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, Double.MIN_VALUE};
			gbl_panel.rowWeights = new double[]{0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, Double.MIN_VALUE};
			panel.setLayout(gbl_panel);
			
			lblNewLabel = new JLabel("Name");
			lblNewLabel.setFont(new Font("Tahoma", Font.BOLD, 20));
			GridBagConstraints gbc_lblNewLabel = new GridBagConstraints();
			gbc_lblNewLabel.anchor = GridBagConstraints.WEST;
			gbc_lblNewLabel.insets = new Insets(0, 0, 5, 5);
			gbc_lblNewLabel.gridx = 2;
			gbc_lblNewLabel.gridy = 2;
			panel.add(lblNewLabel, gbc_lblNewLabel);
			
			nameText = new JTextField();
			nameText.setFont(new Font("Tahoma", Font.PLAIN, 20));
			GridBagConstraints gbc_nameText = new GridBagConstraints();
			gbc_nameText.insets = new Insets(0, 0, 5, 5);
			gbc_nameText.fill = GridBagConstraints.HORIZONTAL;
			gbc_nameText.gridx = 3;
			gbc_nameText.gridy = 2;
			panel.add(nameText, gbc_nameText);
			nameText.setColumns(10);
			
			lblPhone = new JLabel("Phone#");
			lblPhone.setFont(new Font("Tahoma", Font.BOLD, 20));
			GridBagConstraints gbc_lblPhone = new GridBagConstraints();
			gbc_lblPhone.anchor = GridBagConstraints.WEST;
			gbc_lblPhone.insets = new Insets(0, 0, 5, 5);
			gbc_lblPhone.gridx = 2;
			gbc_lblPhone.gridy = 3;
			panel.add(lblPhone, gbc_lblPhone);
			
			phoneText = new JTextField();
			phoneText.setFont(new Font("Tahoma", Font.PLAIN, 20));
			GridBagConstraints gbc_phoneText = new GridBagConstraints();
			gbc_phoneText.insets = new Insets(0, 0, 5, 5);
			gbc_phoneText.fill = GridBagConstraints.HORIZONTAL;
			gbc_phoneText.gridx = 3;
			gbc_phoneText.gridy = 3;
			panel.add(phoneText, gbc_phoneText);
			phoneText.setColumns(10);
			
			lblMemberid = new JLabel("CustomerID");
			lblMemberid.setFont(new Font("Tahoma", Font.BOLD, 20));
			GridBagConstraints gbc_lblMemberid = new GridBagConstraints();
			gbc_lblMemberid.anchor = GridBagConstraints.WEST;
			gbc_lblMemberid.insets = new Insets(0, 0, 5, 5);
			gbc_lblMemberid.gridx = 2;
			gbc_lblMemberid.gridy = 4;
			panel.add(lblMemberid, gbc_lblMemberid);
			
			dateText = new JTextField();
			dateText.setFont(new Font("Tahoma", Font.PLAIN, 20));
			dateText.setColumns(10);
			GridBagConstraints gbc_dateText = new GridBagConstraints();
			gbc_dateText.insets = new Insets(0, 0, 5, 5);
			gbc_dateText.fill = GridBagConstraints.HORIZONTAL;
			gbc_dateText.gridx = 3;
			gbc_dateText.gridy = 4;
			panel.add(dateText, gbc_dateText);
			
			lblDateOfClass = new JLabel("Date of Class");
			lblDateOfClass.setFont(new Font("Tahoma", Font.BOLD, 20));
			GridBagConstraints gbc_lblDateOfClass = new GridBagConstraints();
			gbc_lblDateOfClass.anchor = GridBagConstraints.WEST;
			gbc_lblDateOfClass.insets = new Insets(0, 0, 5, 5);
			gbc_lblDateOfClass.gridx = 2;
			gbc_lblDateOfClass.gridy = 5;
			panel.add(lblDateOfClass, gbc_lblDateOfClass);
			
			txtYyyymmdd = new JTextField();
			txtYyyymmdd.setText("YYYY-MM-DD");
			txtYyyymmdd.setFont(new Font("Tahoma", Font.PLAIN, 20));
			txtYyyymmdd.setColumns(10);
			GridBagConstraints gbc_txtYyyymmdd = new GridBagConstraints();
			gbc_txtYyyymmdd.insets = new Insets(0, 0, 5, 5);
			gbc_txtYyyymmdd.fill = GridBagConstraints.HORIZONTAL;
			gbc_txtYyyymmdd.gridx = 3;
			gbc_txtYyyymmdd.gridy = 5;
			panel.add(txtYyyymmdd, gbc_txtYyyymmdd);
			
			btnNewButton = new JButton("Check Booking");
			btnNewButton.setFont(new Font("Tahoma", Font.PLAIN, 20));
			GridBagConstraints gbc_btnNewButton = new GridBagConstraints();
			gbc_btnNewButton.anchor = GridBagConstraints.WEST;
			gbc_btnNewButton.insets = new Insets(0, 0, 0, 5);
			gbc_btnNewButton.gridx = 2;
			gbc_btnNewButton.gridy = 7;
			panel.add(btnNewButton, gbc_btnNewButton);
			
			
			
			btnNewButton.addActionListener(new ActionListener(){public void actionPerformed(ActionEvent confirmAE){
				
				
				String display = lDBBook.checkBooking(nameText.getText(), phoneText.getText(), dateText.getText());
				
				UIManager.put("OptionPane.messageFont", new Font("TimesNewRoman",Font.BOLD,20));
				UIManager.put("OptionPane.buttonFont", new Font("SansSerif",Font.BOLD,20));
				JOptionPane.showMessageDialog(null,display,"Thank You",JOptionPane.INFORMATION_MESSAGE);
				dispose();
				
				
			
				}
			});
			
			
			LeisureCentre.getAccessibleContext().setAccessibleName("Booking");
			
			setDefaultCloseOperation(DISPOSE_ON_CLOSE);
			setResizable(false);
			pack();
		}// </editor-fold>//GEN-END:initComponents

		/**
		 * @param args the command line arguments
		 */
		public static void main(String args[]) {
			/* Set the Nimbus look and feel */
			//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
			/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
			 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
			 */
			try {
				for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
					if ("Nimbus".equals(info.getName())) {
						javax.swing.UIManager.setLookAndFeel(info.getClassName());
						break;
					}
				}
			} catch (ClassNotFoundException ex) {
				java.util.logging.Logger.getLogger(leisureCentreProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
			} catch (InstantiationException ex) {
				java.util.logging.Logger.getLogger(leisureCentreProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
			} catch (IllegalAccessException ex) {
				java.util.logging.Logger.getLogger(leisureCentreProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
			} catch (javax.swing.UnsupportedLookAndFeelException ex) {
				java.util.logging.Logger.getLogger(leisureCentreProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
			}
			//</editor-fold>

			/* Create and display the form */
			java.awt.EventQueue.invokeLater(new Runnable() {
				public void run() {
					CheckBooking p = new CheckBooking();
					p.setVisible(true);
					p.pack();
					p.setResizable(false);
					
				}
			});
		}

		// Variables declaration - do not modify//GEN-BEGIN:variables
		private javax.swing.JTabbedPane LeisureCentre;
		private javax.swing.JTabbedPane jTabbedPane1;
		private javax.swing.JTabbedPane jTabbedPane6;
		private JPanel panel;
		private JButton btnNewButton;
		private JLabel lblNewLabel;
		private JLabel lblPhone;
		private JTextField nameText;
		private JTextField phoneText;
		private JLabel lblMemberid;
		private JTextField dateText;
		private JLabel lblDateOfClass;
		private JTextField txtYyyymmdd;
	}
