package Leisure;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import java.sql.SQLException;

import java.awt.Toolkit;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.Font;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.JButton;
import javax.swing.JComboBox;
import java.awt.GridBagLayout;
import java.awt.GridBagConstraints;
import java.awt.Insets;

import com.toedter.calendar.JDateChooser;

import javax.swing.JTable;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;
import javax.swing.JTextArea;
/**
 *
 * @author l00115280
 */
public class leisureCentreProject extends javax.swing.JFrame {

	/**
	 * 
	 */
	private leisure_DB lDB = new leisure_DB();
	private JDateChooser dateChooser = new JDateChooser();
	private static final long serialVersionUID = 1L;
	/**
	 * Creates new form leisureCentreProject
	 * @throws SQLException 
	 */
	public leisureCentreProject() throws SQLException {
		initComponents();
		this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.png")));
	}

	/**
	 * This method is called from within the constructor to initialise the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 * @throws SQLException 
	 */
	//@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() throws SQLException {

		setTitle("GOBO LEISURE");

		Font tabFont = new Font("Tahoma",Font.BOLD|Font.ITALIC,18);

		table_1 = lDB.makeScheduleTable(lDB.today());		
		table_2 = lDB.makeScheduleTable(lDB.today());

		jTabbedPane6 = new javax.swing.JTabbedPane();

		jTabbedPane6.setFont(tabFont);

		jTabbedPane1 = new javax.swing.JTabbedPane();

		jTabbedPane1.setFont(tabFont);



		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		GridBagLayout gridBagLayout = new GridBagLayout();
		gridBagLayout.columnWidths = new int[]{787, 0};
		gridBagLayout.rowHeights = new int[]{597, 0};
		gridBagLayout.columnWeights = new double[]{0.0, Double.MIN_VALUE};
		gridBagLayout.rowWeights = new double[]{0.0, Double.MIN_VALUE};
		getContentPane().setLayout(gridBagLayout);

		dateChooser.setFont(new Font("Tahoma",Font.ITALIC,16));

		LeisureCentre = new javax.swing.JTabbedPane();

		LeisureCentre.setFont(tabFont);

		jPanel1 = new javax.swing.JPanel();
		jComboBox1 = new javax.swing.JComboBox<>();
		jComboBox1.setFont(new Font("Tahoma", Font.ITALIC, 18));
		jButton1 = new javax.swing.JButton();
		jButton1.setFont(new Font("Tahoma", Font.BOLD, 18));


		jTabbedPane3 = new javax.swing.JTabbedPane();

		jTabbedPane3.setFont(tabFont);

				jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(lDB.getClasses()));
		jComboBox1.setEnabled(true);
		jButton1.setText("Check Availability");


		dateChooser.setEnabled(true);
		jButton1.setEnabled(true);



		JLabel lblActivities = new JLabel("Classes:");
		lblActivities.setFont(new Font("Tahoma", Font.BOLD, 19));

		lblNewLabel = new JLabel("Please Select a Date");
		lblNewLabel.setFont(new Font("Tahoma", Font.BOLD, 19));


		JScrollPane scrollPane = new JScrollPane();
		
		JLabel label_6 = new JLabel("All Classes on: " + lDB.today());
		label_6.setFont(new Font("Tahoma", Font.BOLD, 19));
		
		JButton btnNewButton = new JButton("Check Bookings");
		btnNewButton.setFont(new Font("Tahoma", Font.BOLD, 18));
		
		btnNewButton.addActionListener(new ActionListener() {
		public void actionPerformed(ActionEvent confirmAE){


			try{

				CheckBooking c = new CheckBooking();
				
				c.setVisible(true);

			}
			catch(Exception e){
				System.out.println(e.getMessage());
			}
			finally{

			}

		}} );


		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1Layout.setHorizontalGroup(
			jPanel1Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
					.addGap(35)
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup()
							.addComponent(label_6, GroupLayout.PREFERRED_SIZE, 302, GroupLayout.PREFERRED_SIZE)
							.addContainerGap())
						.addGroup(jPanel1Layout.createSequentialGroup()
							.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
								.addComponent(scrollPane, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 725, Short.MAX_VALUE)
								.addGroup(jPanel1Layout.createSequentialGroup()
									.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING, false)
										.addComponent(jComboBox1, 0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(lblActivities, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
									.addPreferredGap(ComponentPlacement.RELATED, 212, Short.MAX_VALUE)
									.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING, false)
										.addComponent(lblNewLabel, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(dateChooser, Alignment.LEADING, GroupLayout.PREFERRED_SIZE, 331, GroupLayout.PREFERRED_SIZE)
										.addComponent(jButton1, Alignment.LEADING, GroupLayout.PREFERRED_SIZE, 250, GroupLayout.PREFERRED_SIZE)))
								.addComponent(btnNewButton))
							.addGap(56))))
		);
		jPanel1Layout.setVerticalGroup(
			jPanel1Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
					.addGap(63)
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup()
							.addComponent(lblActivities)
							.addPreferredGap(ComponentPlacement.RELATED)
							.addComponent(jComboBox1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
						.addGroup(jPanel1Layout.createSequentialGroup()
							.addComponent(lblNewLabel)
							.addGap(14)
							.addComponent(dateChooser, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
							.addGap(18)
							.addComponent(jButton1)))
					.addGap(21)
					.addComponent(label_6, GroupLayout.PREFERRED_SIZE, 23, GroupLayout.PREFERRED_SIZE)
					.addGap(18)
					.addComponent(scrollPane, GroupLayout.PREFERRED_SIZE, 197, GroupLayout.PREFERRED_SIZE)
					.addGap(41)
					.addComponent(btnNewButton)
					.addContainerGap(59, Short.MAX_VALUE))
		);

		jButton1.addActionListener(new ActionListener() {@SuppressWarnings({ "deprecation", "static-access" })
		public void actionPerformed(ActionEvent confirmAE){

			//yyyy-mm-dd

			//1900
			//1

			try{
				int cIdent = 0;

				// plus one because combobox is zero deliminated
				cIdent = jComboBox1.getSelectedIndex() + 1;

				int year,month,day;
				String sDay,sMonth,sFinalDate = null;
				day = dateChooser.getDate().getDate();
				month = dateChooser.getDate().getMonth() + 1;
				year = dateChooser.getDate().getYear() + 1900;


				if(day < 10){
					sDay = "0" + day;
				}
				else{
					sDay = Integer.toString(day);
				}
				if(month < 10){
					sMonth = "0" + month;
				}
				else{
					sMonth = Integer.toString(month);
				}

				sFinalDate = year + "-" + sMonth + "-" + sDay;	
				
				label_6.setText("Schedule for: " + sFinalDate);
				
				table_1 = lDB.makeScheduleTable(sFinalDate);
				scrollPane.setViewportView(table_1);
				//Tester stuff making sure outputs are as they should be
				System.out.println(lDB.isFull(cIdent, sFinalDate));

				System.out.print(sFinalDate+"\n");


				if(lDB.isFull(cIdent,sFinalDate)){

					UIManager.put("OptionPane.messageFont", new Font("TimesNewRoman",Font.BOLD,20));
					UIManager.put("OptionPane.buttonFont", new Font("SansSerif",Font.BOLD,20));
					JOptionPane.showMessageDialog(null,"Sorry! No Booking available.","Please Try Again",JOptionPane.INFORMATION_MESSAGE);
				}
				else{
					UIManager.put("OptionPane.messageFont", new Font("TimesNewRoman",Font.BOLD,20));
					UIManager.put("OptionPane.buttonFont", new Font("SansSerif",Font.BOLD,20));
					
					String[] op = {"OK","Cancel"};
					
					int bookingInt = JOptionPane.showOptionDialog(null,"Would you like to confirm booking","Continue to Booking",JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE,null,op,null);
					if(bookingInt == JOptionPane.OK_OPTION){
						BookingPage bp = new BookingPage();
						
						//bp.main(null);
						bp.setClassType(""+cIdent);
						bp.setDate(sFinalDate);
						bp.setVisible(true);
					}
				
				
				}
			}
			catch(Exception e){
				System.out.println(e.getMessage());
				UIManager.put("OptionPane.messageFont", new Font("TimesNewRoman",Font.BOLD,20));
				UIManager.put("OptionPane.buttonFont", new Font("SansSerif",Font.BOLD,20));
				JOptionPane.showMessageDialog(null,"NO DATE SELECTED!","Please Try Again",JOptionPane.WARNING_MESSAGE);
			}
			finally{

			}

		}} );


		


		jPanel3 = new javax.swing.JPanel();



		LeisureCentre.addTab("Timetable", jPanel3);
		
		JLabel label_35 = new JLabel("Schedule for: " + lDB.today());
		label_35.setFont(new Font("Tahoma", Font.BOLD, 19));
		
		scrollPane_1 = new JScrollPane();

		scrollPane_1.setViewportView(table_2);
		
		JDateChooser dateChooser_1 = new JDateChooser();
		dateChooser_1.setFont(new Font("Tahoma", Font.ITALIC, 18));
		dateChooser_1.setEnabled(true);
		
		JLabel lblNewLabel_1 = new JLabel("Select A Date to View Schedule");
		lblNewLabel_1.setFont(new Font("Tahoma", Font.PLAIN, 20));
		
		JButton scheduleBtn = new JButton("Confirm Date");
		scheduleBtn.setFont(new Font("Tahoma", Font.BOLD, 18));
		GroupLayout gl_jPanel3 = new GroupLayout(jPanel3);
		gl_jPanel3.setHorizontalGroup(
			gl_jPanel3.createParallelGroup(Alignment.LEADING)
				.addGroup(Alignment.TRAILING, gl_jPanel3.createSequentialGroup()
					.addGap(78)
					.addGroup(gl_jPanel3.createParallelGroup(Alignment.TRAILING)
						.addComponent(scrollPane_1, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 617, Short.MAX_VALUE)
						.addComponent(label_35, Alignment.LEADING)
						.addGroup(gl_jPanel3.createSequentialGroup()
							.addComponent(lblNewLabel_1)
							.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
							.addGroup(gl_jPanel3.createParallelGroup(Alignment.LEADING)
								.addComponent(scheduleBtn)
								.addComponent(dateChooser_1, GroupLayout.PREFERRED_SIZE, 331, GroupLayout.PREFERRED_SIZE))))
					.addGap(121))
		);
		gl_jPanel3.setVerticalGroup(
			gl_jPanel3.createParallelGroup(Alignment.LEADING)
				.addGroup(gl_jPanel3.createSequentialGroup()
					.addGap(40)
					.addComponent(label_35)
					.addGap(18)
					.addComponent(scrollPane_1, GroupLayout.PREFERRED_SIZE, 146, GroupLayout.PREFERRED_SIZE)
					.addGap(29)
					.addGroup(gl_jPanel3.createParallelGroup(Alignment.TRAILING)
						.addComponent(dateChooser_1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
						.addComponent(lblNewLabel_1))
					.addPreferredGap(ComponentPlacement.RELATED)
					.addComponent(scheduleBtn)
					.addGap(241))
		);
		jPanel3.setLayout(gl_jPanel3);
		


		scrollPane.setViewportView(table_1);


		jPanel1.setLayout(jPanel1Layout);

		LeisureCentre.addTab("Booking", jPanel1);

		//ButtonGroup bGroup = new ButtonGroup();

		JPanel panel_2 = new JPanel();
		LeisureCentre.addTab("Admin Login", null, panel_2, null);
		GridBagLayout gbl_panel_2 = new GridBagLayout();
		gbl_panel_2.columnWidths = new int[]{70, 88, 85, 0, 155, 0};
		gbl_panel_2.rowHeights = new int[]{49, 27, 35, 26, 37, 26, 29, 0};
		gbl_panel_2.columnWeights = new double[]{0.0, 0.0, 0.0, 0.0, 0.0, Double.MIN_VALUE};
		gbl_panel_2.rowWeights = new double[]{0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, Double.MIN_VALUE};
		panel_2.setLayout(gbl_panel_2);

		JLabel lblLogin = new JLabel();
		lblLogin.setText("Login ");
		lblLogin.setFont(new Font("Tahoma", Font.BOLD, 22));
		GridBagConstraints gbc_lblLogin = new GridBagConstraints();
		gbc_lblLogin.anchor = GridBagConstraints.NORTHWEST;
		gbc_lblLogin.insets = new Insets(0, 0, 5, 0);
		gbc_lblLogin.gridwidth = 2;
		gbc_lblLogin.gridx = 3;
		gbc_lblLogin.gridy = 1;
		panel_2.add(lblLogin, gbc_lblLogin);

		JLabel lblName = new JLabel();
		lblName.setText("Staff ID");
		lblName.setFont(new Font("Tahoma", Font.PLAIN, 18));
		GridBagConstraints gbc_lblName = new GridBagConstraints();
		gbc_lblName.anchor = GridBagConstraints.NORTHWEST;
		gbc_lblName.insets = new Insets(0, 0, 5, 5);
		gbc_lblName.gridx = 3;
		gbc_lblName.gridy = 3;
		panel_2.add(lblName, gbc_lblName);

		loginID = new JTextField();
		loginID.setFont(new Font("Tahoma", Font.PLAIN, 18));
		loginID.setText("Enter ID");
		GridBagConstraints gbc_loginID = new GridBagConstraints();
		gbc_loginID.anchor = GridBagConstraints.NORTH;
		gbc_loginID.fill = GridBagConstraints.HORIZONTAL;
		gbc_loginID.insets = new Insets(0, 0, 5, 0);
		gbc_loginID.gridx = 4;
		gbc_loginID.gridy = 3;
		panel_2.add(loginID, gbc_loginID);

		JLabel lblPassword = new JLabel();
		lblPassword.setText("Password");
		lblPassword.setFont(new Font("Tahoma", Font.PLAIN, 18));
		GridBagConstraints gbc_lblPassword = new GridBagConstraints();
		gbc_lblPassword.anchor = GridBagConstraints.NORTHWEST;
		gbc_lblPassword.insets = new Insets(0, 0, 5, 5);
		gbc_lblPassword.gridx = 3;
		gbc_lblPassword.gridy = 4;
		panel_2.add(lblPassword, gbc_lblPassword);

		loginPassword = new JPasswordField();
		loginPassword.setFont(new Font("Tahoma", Font.PLAIN, 18));
		loginPassword.setText("password");
		GridBagConstraints gbc_loginPassword = new GridBagConstraints();
		gbc_loginPassword.anchor = GridBagConstraints.NORTH;
		gbc_loginPassword.fill = GridBagConstraints.HORIZONTAL;
		gbc_loginPassword.insets = new Insets(0, 0, 5, 0);
		gbc_loginPassword.gridx = 4;
		gbc_loginPassword.gridy = 4;
		panel_2.add(loginPassword, gbc_loginPassword);

		JButton btnConfirmLogin = new JButton();
		btnConfirmLogin.setFont(new Font("Tahoma", Font.PLAIN, 20));
		btnConfirmLogin.setText("Confirm Login");
		GridBagConstraints gbc_btnConfirmLogin = new GridBagConstraints();
		gbc_btnConfirmLogin.insets = new Insets(0, 0, 5, 5);
		gbc_btnConfirmLogin.anchor = GridBagConstraints.NORTHWEST;
		gbc_btnConfirmLogin.gridx = 3;
		gbc_btnConfirmLogin.gridy = 5;
		panel_2.add(btnConfirmLogin, gbc_btnConfirmLogin);
		LeisureCentre.addTab("Membership", jTabbedPane3);
		jPanel2 = new javax.swing.JPanel();	

		jTabbedPane3.addTab("New Member", jPanel2);
		GridBagLayout gbl_jPanel2 = new GridBagLayout();
		gbl_jPanel2.columnWidths = new int[] {21, 97, 165, 43, 0, 52};
		gbl_jPanel2.rowHeights = new int[]{26, 26, 43, 39, 26, 33, 0, 33, 33, 33, 35, 0};
		gbl_jPanel2.columnWeights = new double[]{0.0, 0.0, 0.0, 0.0, 0.0, 0.0};
		gbl_jPanel2.rowWeights = new double[]{0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, Double.MIN_VALUE};
		jPanel2.setLayout(gbl_jPanel2);
		jLabel9 = new javax.swing.JLabel();
		jLabel9.setFont(new Font("Tahoma", Font.BOLD, 22));

		jLabel9.setText("Member Details");
		GridBagConstraints gbc_jLabel9 = new GridBagConstraints();
		gbc_jLabel9.anchor = GridBagConstraints.NORTHWEST;
		gbc_jLabel9.insets = new Insets(0, 0, 5, 5);
		gbc_jLabel9.gridx = 1;
		gbc_jLabel9.gridy = 1;
		jPanel2.add(jLabel9, gbc_jLabel9);
		jLabel10 = new javax.swing.JLabel();
		jLabel10.setFont(new Font("Tahoma", Font.BOLD, 22));

		jLabel10.setText("Membership Details");
		GridBagConstraints gbc_jLabel10 = new GridBagConstraints();
		gbc_jLabel10.anchor = GridBagConstraints.SOUTHWEST;
		gbc_jLabel10.insets = new Insets(0, 0, 5, 5);
		gbc_jLabel10.gridx = 4;
		gbc_jLabel10.gridy = 1;
		jPanel2.add(jLabel10, gbc_jLabel10);
		jLabel11 = new javax.swing.JLabel();
		jLabel11.setFont(new Font("Tahoma", Font.PLAIN, 18));

		jLabel11.setText("Membership type:");
		GridBagConstraints gbc_jLabel11 = new GridBagConstraints();
		gbc_jLabel11.anchor = GridBagConstraints.NORTHWEST;
		gbc_jLabel11.insets = new Insets(0, 0, 5, 5);
		gbc_jLabel11.gridx = 4;
		gbc_jLabel11.gridy = 2;
		jPanel2.add(jLabel11, gbc_jLabel11);
		jLabel3 = new javax.swing.JLabel();
		jLabel3.setFont(new Font("Tahoma", Font.PLAIN, 18));

		jLabel3.setText("First Name");
		GridBagConstraints gbc_jLabel3 = new GridBagConstraints();
		gbc_jLabel3.fill = GridBagConstraints.HORIZONTAL;
		gbc_jLabel3.insets = new Insets(0, 0, 5, 5);
		gbc_jLabel3.gridx = 1;
		gbc_jLabel3.gridy = 3;
		jPanel2.add(jLabel3, gbc_jLabel3);
		addMemFiNa = new javax.swing.JTextField();
		addMemFiNa.setFont(new Font("Tahoma", Font.PLAIN, 18));
		GridBagConstraints gbc_addMemFiNa = new GridBagConstraints();
		gbc_addMemFiNa.fill = GridBagConstraints.HORIZONTAL;
		gbc_addMemFiNa.insets = new Insets(0, 0, 5, 5);
		gbc_addMemFiNa.gridx = 2;
		gbc_addMemFiNa.gridy = 3;
		jPanel2.add(addMemFiNa, gbc_addMemFiNa);
		jComboBox7 = new javax.swing.JComboBox<>();
		jComboBox7.setFont(new Font("Tahoma", Font.PLAIN, 18));

		jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(lDB.getMemberships()));
		jComboBox7.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jComboBox7ActionPerformed(evt);
			}
		});
		GridBagConstraints gbc_jComboBox7 = new GridBagConstraints();
		gbc_jComboBox7.anchor = GridBagConstraints.WEST;
		gbc_jComboBox7.insets = new Insets(0, 0, 5, 5);
		gbc_jComboBox7.gridx = 4;
		gbc_jComboBox7.gridy = 3;
		jPanel2.add(jComboBox7, gbc_jComboBox7);
		jLabel4 = new javax.swing.JLabel();
		jLabel4.setFont(new Font("Tahoma", Font.PLAIN, 18));

		jLabel4.setText("Surname");
		GridBagConstraints gbc_jLabel4 = new GridBagConstraints();
		gbc_jLabel4.anchor = GridBagConstraints.WEST;
		gbc_jLabel4.insets = new Insets(0, 0, 5, 5);
		gbc_jLabel4.gridx = 1;
		gbc_jLabel4.gridy = 4;
		jPanel2.add(jLabel4, gbc_jLabel4);
		addMemLaNa = new javax.swing.JTextField();
		addMemLaNa.setFont(new Font("Tahoma", Font.PLAIN, 18));
		GridBagConstraints gbc_addMemLaNa = new GridBagConstraints();
		gbc_addMemLaNa.fill = GridBagConstraints.HORIZONTAL;
		gbc_addMemLaNa.insets = new Insets(0, 0, 5, 5);
		gbc_addMemLaNa.gridx = 2;
		gbc_addMemLaNa.gridy = 4;
		jPanel2.add(addMemLaNa, gbc_addMemLaNa);
		jLabel5 = new javax.swing.JLabel();
		jLabel5.setFont(new Font("Tahoma", Font.PLAIN, 18));

		jLabel5.setText("Address");
		GridBagConstraints gbc_jLabel5 = new GridBagConstraints();
		gbc_jLabel5.anchor = GridBagConstraints.WEST;
		gbc_jLabel5.insets = new Insets(0, 0, 5, 5);
		gbc_jLabel5.gridx = 1;
		gbc_jLabel5.gridy = 5;
		jPanel2.add(jLabel5, gbc_jLabel5);
		addMemAd = new javax.swing.JTextField();
		addMemAd.setFont(new Font("Tahoma", Font.PLAIN, 18));
		GridBagConstraints gbc_addMemAd = new GridBagConstraints();
		gbc_addMemAd.fill = GridBagConstraints.HORIZONTAL;
		gbc_addMemAd.insets = new Insets(0, 0, 5, 5);
		gbc_addMemAd.gridx = 2;
		gbc_addMemAd.gridy = 5;
		jPanel2.add(addMemAd, gbc_addMemAd);
		jLabel7 = new javax.swing.JLabel();
		jLabel7.setFont(new Font("Tahoma", Font.PLAIN, 18));

		jLabel7.setText("Phone #");
		GridBagConstraints gbc_jLabel7 = new GridBagConstraints();
		gbc_jLabel7.anchor = GridBagConstraints.WEST;
		gbc_jLabel7.insets = new Insets(0, 0, 5, 5);
		gbc_jLabel7.gridx = 1;
		gbc_jLabel7.gridy = 6;
		jPanel2.add(jLabel7, gbc_jLabel7);
		addMemPhone = new javax.swing.JTextField();
		addMemPhone.setFont(new Font("Tahoma", Font.PLAIN, 18));
		GridBagConstraints gbc_addMemPhone = new GridBagConstraints();
		gbc_addMemPhone.fill = GridBagConstraints.HORIZONTAL;
		gbc_addMemPhone.insets = new Insets(0, 0, 5, 5);
		gbc_addMemPhone.gridx = 2;
		gbc_addMemPhone.gridy = 6;
		jPanel2.add(addMemPhone, gbc_addMemPhone);
		jLabel8 = new javax.swing.JLabel();
		jLabel8.setFont(new Font("Tahoma", Font.PLAIN, 18));

		jLabel8.setText("D.O.B");
		GridBagConstraints gbc_jLabel8 = new GridBagConstraints();
		gbc_jLabel8.anchor = GridBagConstraints.WEST;
		gbc_jLabel8.insets = new Insets(0, 0, 5, 5);
		gbc_jLabel8.gridx = 1;
		gbc_jLabel8.gridy = 7;
		jPanel2.add(jLabel8, gbc_jLabel8);
		addMemDOB = new javax.swing.JTextField();
		addMemDOB.setFont(new Font("Tahoma", Font.PLAIN, 18));
		addMemDOB.setText("YYYY-MM-DD");
		GridBagConstraints gbc_addMemDOB = new GridBagConstraints();
		gbc_addMemDOB.fill = GridBagConstraints.HORIZONTAL;
		gbc_addMemDOB.insets = new Insets(0, 0, 5, 5);
		gbc_addMemDOB.gridx = 2;
		gbc_addMemDOB.gridy = 7;
		jPanel2.add(addMemDOB, gbc_addMemDOB);
		jButton2 = new javax.swing.JButton();
		jButton2.setFont(new Font("Tahoma", Font.PLAIN, 18));

		jButton2.setText("Create Member");
		jButton2.addActionListener(new java.awt.event.ActionListener() {

			public void actionPerformed(java.awt.event.ActionEvent evt) {



				String fn, ln, ad, ph, dBirth;
				Double bal = 0.0;
				int memType = lDB.getMembershipType((String) jComboBox7.getSelectedItem());
				dBirth = addMemDOB.getText();	
				fn = addMemFiNa.getText();
				ln = addMemLaNa.getText();
				ad = addMemAd.getText();
				ph = addMemPhone.getText();


				lDB.addMember(memType, fn, ln, dBirth, ad, ph, bal);
				UIManager.put("OptionPane.messageFont", new Font("TimesNewRoman",Font.BOLD,20));
				UIManager.put("OptionPane.buttonFont", new Font("SansSerif",Font.BOLD,20));
				JOptionPane.showMessageDialog(null,"New Member created.","Success",JOptionPane.INFORMATION_MESSAGE);

				addMemDOB.setText(null);
				addMemFiNa.setText(null);
				addMemLaNa.setText(null);
				addMemAd.setText(null);
				addMemPhone.setText(null);

				jButton2ActionPerformed(evt);
			}
		});
		GridBagConstraints gbc_jButton2 = new GridBagConstraints();
		gbc_jButton2.fill = GridBagConstraints.HORIZONTAL;
		gbc_jButton2.insets = new Insets(0, 0, 5, 5);
		gbc_jButton2.gridx = 4;
		gbc_jButton2.gridy = 7;
		jPanel2.add(jButton2, gbc_jButton2);

		panel = new JPanel();
		jTabbedPane3.addTab("Edit Memeber", null, panel, null);
		GridBagLayout gbl_panel = new GridBagLayout();
		gbl_panel.columnWidths = new int[] {30, 30, 160, 30, 167, 81, 30, 82};
		gbl_panel.rowHeights = new int[]{27, 0, 26, 29, 29, 26, 26, 26, 26, 39, 0, 0};
		gbl_panel.columnWeights = new double[]{0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0};
		gbl_panel.rowWeights = new double[]{0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, Double.MIN_VALUE};
		panel.setLayout(gbl_panel);

		label = new JLabel();
		label.setText("Member To Update");
		label.setFont(new Font("Tahoma", Font.BOLD, 22));
		GridBagConstraints gbc_label = new GridBagConstraints();
		gbc_label.anchor = GridBagConstraints.NORTHWEST;
		gbc_label.insets = new Insets(0, 0, 5, 5);
		gbc_label.gridwidth = 3;
		gbc_label.gridx = 1;
		gbc_label.gridy = 1;
		panel.add(label, gbc_label);

		label_9 = new JLabel();
		label_9.setText("Member ID");
		label_9.setFont(new Font("Tahoma", Font.BOLD, 22));
		GridBagConstraints gbc_label_9 = new GridBagConstraints();
		gbc_label_9.anchor = GridBagConstraints.NORTHWEST;
		gbc_label_9.insets = new Insets(0, 0, 5, 0);
		gbc_label_9.gridwidth = 4;
		gbc_label_9.gridx = 4;
		gbc_label_9.gridy = 1;
		panel.add(label_9, gbc_label_9);

		lblMembershipTypeid = new JLabel();
		lblMembershipTypeid.setText("Membership TypeID");
		lblMembershipTypeid.setFont(new Font("Tahoma", Font.PLAIN, 18));
		GridBagConstraints gbc_lblMembershipTypeid = new GridBagConstraints();
		gbc_lblMembershipTypeid.anchor = GridBagConstraints.WEST;
		gbc_lblMembershipTypeid.insets = new Insets(0, 0, 5, 5);
		gbc_lblMembershipTypeid.gridx = 1;
		gbc_lblMembershipTypeid.gridy = 3;
		panel.add(lblMembershipTypeid, gbc_lblMembershipTypeid);

		memShip = new JTextField();
		memShip.setFont(new Font("Tahoma", Font.PLAIN, 18));
		GridBagConstraints gbc_memShip = new GridBagConstraints();
		gbc_memShip.insets = new Insets(0, 0, 5, 5);
		gbc_memShip.fill = GridBagConstraints.HORIZONTAL;
		gbc_memShip.gridx = 2;
		gbc_memShip.gridy = 3;
		panel.add(memShip, gbc_memShip);

		label_3 = new JLabel();
		label_3.setFont(new Font("Tahoma", Font.PLAIN, 18));
		label_3.setText("Mem Id");
		GridBagConstraints gbc_label_3 = new GridBagConstraints();
		gbc_label_3.anchor = GridBagConstraints.NORTHWEST;
		gbc_label_3.insets = new Insets(0, 0, 5, 5);
		gbc_label_3.gridx = 4;
		gbc_label_3.gridy = 3;
		panel.add(label_3, gbc_label_3);

		textField = new JTextField();
		textField.setFont(new Font("Tahoma", Font.PLAIN, 18));
		GridBagConstraints gbc_textField = new GridBagConstraints();
		gbc_textField.fill = GridBagConstraints.HORIZONTAL;
		gbc_textField.anchor = GridBagConstraints.NORTH;
		gbc_textField.insets = new Insets(0, 0, 5, 0);
		gbc_textField.gridwidth = 3;
		gbc_textField.gridx = 5;
		gbc_textField.gridy = 3;
		panel.add(textField, gbc_textField);

		JButton button_1 = new JButton();
		button_1.setFont(new Font("Tahoma", Font.PLAIN, 20));



		button_1.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {

				int in =	Integer.parseInt(textField.getText());

				String init = lDB.getMemDetails(in);
				String[] end = init.split("/");
				String meID = end[0];
				String fName = end[1];
				String lName = end[2];
				String add = end[3];
				String phone = end[4];
				String dob = end[5];


				memShip.setText(meID);
				textField_2.setText(fName);
				textField_3.setText(lName);
				textField_4.setText(add);
				textField_5.setText(phone);
				textField_6.setText(dob);




			}
		});

		label_7 = new JLabel();
		label_7.setFont(new Font("Tahoma", Font.PLAIN, 18));
		label_7.setText("First Name");
		GridBagConstraints gbc_label_7 = new GridBagConstraints();
		gbc_label_7.anchor = GridBagConstraints.WEST;
		gbc_label_7.insets = new Insets(0, 0, 5, 5);
		gbc_label_7.gridx = 1;
		gbc_label_7.gridy = 4;
		panel.add(label_7, gbc_label_7);

		textField_2 = new JTextField();
		textField_2.setFont(new Font("Tahoma", Font.PLAIN, 18));
		GridBagConstraints gbc_textField_2 = new GridBagConstraints();
		gbc_textField_2.anchor = GridBagConstraints.NORTH;
		gbc_textField_2.fill = GridBagConstraints.HORIZONTAL;
		gbc_textField_2.insets = new Insets(0, 0, 5, 5);
		gbc_textField_2.gridx = 2;
		gbc_textField_2.gridy = 4;
		panel.add(textField_2, gbc_textField_2);






		button_1.setText("Confirm Member");
		GridBagConstraints gbc_button_1 = new GridBagConstraints();
		gbc_button_1.anchor = GridBagConstraints.NORTHWEST;
		gbc_button_1.insets = new Insets(0, 0, 5, 5);
		gbc_button_1.gridx = 4;
		gbc_button_1.gridy = 4;
		panel.add(button_1, gbc_button_1);

		label_8 = new JLabel();
		label_8.setFont(new Font("Tahoma", Font.PLAIN, 18));
		label_8.setText("Surname");
		GridBagConstraints gbc_label_8 = new GridBagConstraints();
		gbc_label_8.anchor = GridBagConstraints.NORTHWEST;
		gbc_label_8.insets = new Insets(0, 0, 5, 5);
		gbc_label_8.gridx = 1;
		gbc_label_8.gridy = 5;
		panel.add(label_8, gbc_label_8);

		textField_3 = new JTextField();
		textField_3.setFont(new Font("Tahoma", Font.PLAIN, 18));
		GridBagConstraints gbc_textField_3 = new GridBagConstraints();
		gbc_textField_3.anchor = GridBagConstraints.SOUTH;
		gbc_textField_3.fill = GridBagConstraints.HORIZONTAL;
		gbc_textField_3.insets = new Insets(0, 0, 5, 5);
		gbc_textField_3.gridx = 2;
		gbc_textField_3.gridy = 5;
		panel.add(textField_3, gbc_textField_3);

		label_4 = new JLabel();
		label_4.setFont(new Font("Tahoma", Font.PLAIN, 18));
		label_4.setText("Address");
		GridBagConstraints gbc_label_4 = new GridBagConstraints();
		gbc_label_4.anchor = GridBagConstraints.NORTHWEST;
		gbc_label_4.insets = new Insets(0, 0, 5, 5);
		gbc_label_4.gridx = 1;
		gbc_label_4.gridy = 6;
		panel.add(label_4, gbc_label_4);

		textField_4 = new JTextField();
		textField_4.setFont(new Font("Tahoma", Font.PLAIN, 18));
		GridBagConstraints gbc_textField_4 = new GridBagConstraints();
		gbc_textField_4.anchor = GridBagConstraints.NORTH;
		gbc_textField_4.fill = GridBagConstraints.HORIZONTAL;
		gbc_textField_4.insets = new Insets(0, 0, 5, 5);
		gbc_textField_4.gridx = 2;
		gbc_textField_4.gridy = 6;
		panel.add(textField_4, gbc_textField_4);

		lblPhone = new JLabel();
		lblPhone.setFont(new Font("Tahoma", Font.PLAIN, 18));
		lblPhone.setText("Phone #");
		GridBagConstraints gbc_lblPhone = new GridBagConstraints();
		gbc_lblPhone.anchor = GridBagConstraints.NORTHWEST;
		gbc_lblPhone.insets = new Insets(0, 0, 5, 5);
		gbc_lblPhone.gridx = 1;
		gbc_lblPhone.gridy = 7;
		panel.add(lblPhone, gbc_lblPhone);

		textField_5 = new JTextField();
		textField_5.setFont(new Font("Tahoma", Font.PLAIN, 18));
		GridBagConstraints gbc_textField_5 = new GridBagConstraints();
		gbc_textField_5.anchor = GridBagConstraints.NORTH;
		gbc_textField_5.fill = GridBagConstraints.HORIZONTAL;
		gbc_textField_5.insets = new Insets(0, 0, 5, 5);
		gbc_textField_5.gridx = 2;
		gbc_textField_5.gridy = 7;
		panel.add(textField_5, gbc_textField_5);

		label_2 = new JLabel();
		label_2.setFont(new Font("Tahoma", Font.PLAIN, 18));
		label_2.setText("D.O.B");
		GridBagConstraints gbc_label_2 = new GridBagConstraints();
		gbc_label_2.anchor = GridBagConstraints.NORTHWEST;
		gbc_label_2.insets = new Insets(0, 0, 5, 5);
		gbc_label_2.gridx = 1;
		gbc_label_2.gridy = 8;
		panel.add(label_2, gbc_label_2);

		textField_6 = new JTextField();
		textField_6.setFont(new Font("Tahoma", Font.PLAIN, 18));
		GridBagConstraints gbc_textField_6 = new GridBagConstraints();
		gbc_textField_6.anchor = GridBagConstraints.NORTH;
		gbc_textField_6.fill = GridBagConstraints.HORIZONTAL;
		gbc_textField_6.insets = new Insets(0, 0, 5, 5);
		gbc_textField_6.gridx = 2;
		gbc_textField_6.gridy = 8;
		panel.add(textField_6, gbc_textField_6);

		button = new JButton();
		button.setFont(new Font("Tahoma", Font.PLAIN, 20));


		button.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {

				int mem = Integer.parseInt(textField.getText());
				int mShip = Integer.parseInt(memShip.getText());

				lDB.editMember(mem, mShip, textField_2.getText(), textField_3.getText(), textField_6.getText(), textField_4.getText(), textField_5.getText());

				UIManager.put("OptionPane.messageFont", new Font("TimesNewRoman",Font.BOLD,20));
				UIManager.put("OptionPane.buttonFont", new Font("SansSerif",Font.BOLD,20));
				JOptionPane.showMessageDialog(null,"Member: "+ textField_2.getText() + " " + textField_3.getText() + " Updated","Successful Update",JOptionPane.INFORMATION_MESSAGE);




				memShip.setText("");
				textField.setText("");
				textField_2.setText("");
				textField_3.setText("");
				textField_4.setText("");
				textField_5.setText("");
				textField_6.setText("");
			}
		});
		button.setText("Update Member");
		GridBagConstraints gbc_button = new GridBagConstraints();
		gbc_button.anchor = GridBagConstraints.WEST;
		gbc_button.fill = GridBagConstraints.VERTICAL;
		gbc_button.insets = new Insets(0, 0, 5, 5);
		gbc_button.gridx = 1;
		gbc_button.gridy = 9;
		panel.add(button, gbc_button);

		panel_1 = new JPanel();
		jTabbedPane3.addTab("Delete Member", null, panel_1, null);
		GridBagLayout gbl_panel_1 = new GridBagLayout();
		gbl_panel_1.columnWidths = new int[]{30, 30, 160, 30, 167, 81, 30, 82, 0};
		gbl_panel_1.rowHeights = new int[]{27, 0, 26, 36, 29, 26, 26, 26, 26, 39, 0};
		gbl_panel_1.columnWeights = new double[]{0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, Double.MIN_VALUE};
		gbl_panel_1.rowWeights = new double[]{0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, Double.MIN_VALUE};
		panel_1.setLayout(gbl_panel_1);

		lblMemberToDelete = new JLabel();
		lblMemberToDelete.setText("Member To Delete");
		lblMemberToDelete.setFont(new Font("Tahoma", Font.BOLD, 22));
		GridBagConstraints gbc_lblMemberToDelete = new GridBagConstraints();
		gbc_lblMemberToDelete.anchor = GridBagConstraints.NORTHWEST;
		gbc_lblMemberToDelete.gridwidth = 3;
		gbc_lblMemberToDelete.insets = new Insets(0, 0, 5, 5);
		gbc_lblMemberToDelete.gridx = 1;
		gbc_lblMemberToDelete.gridy = 1;
		panel_1.add(lblMemberToDelete, gbc_lblMemberToDelete);

		lblMemberId = new JLabel();
		lblMemberId.setText("Member ID");
		lblMemberId.setFont(new Font("Tahoma", Font.PLAIN, 18));
		GridBagConstraints gbc_lblMemberId = new GridBagConstraints();
		gbc_lblMemberId.fill = GridBagConstraints.HORIZONTAL;
		gbc_lblMemberId.anchor = GridBagConstraints.NORTH;
		gbc_lblMemberId.insets = new Insets(0, 0, 5, 5);
		gbc_lblMemberId.gridx = 1;
		gbc_lblMemberId.gridy = 3;
		panel_1.add(lblMemberId, gbc_lblMemberId);

		memToDel = new JTextField();
		memToDel.setFont(new Font("Tahoma", Font.PLAIN, 18));
		GridBagConstraints gbc_memToDel = new GridBagConstraints();
		gbc_memToDel.fill = GridBagConstraints.HORIZONTAL;
		gbc_memToDel.anchor = GridBagConstraints.NORTH;
		gbc_memToDel.insets = new Insets(0, 0, 5, 5);
		gbc_memToDel.gridx = 2;
		gbc_memToDel.gridy = 3;
		panel_1.add(memToDel, gbc_memToDel);

		delMemDetails = new JTextArea();
		delMemDetails.setWrapStyleWord(true);
		delMemDetails.setLineWrap(true);
		delMemDetails.setEditable(false);
		delMemDetails.setFont(new Font("Tahoma", Font.BOLD, 19));
		delMemDetails.setText("Member Details");
		GridBagConstraints gbc_delMemDetails = new GridBagConstraints();
		gbc_delMemDetails.gridwidth = 2;
		gbc_delMemDetails.fill = GridBagConstraints.BOTH;
		gbc_delMemDetails.gridheight = 3;
		gbc_delMemDetails.insets = new Insets(0, 0, 5, 5);
		gbc_delMemDetails.gridx = 4;
		gbc_delMemDetails.gridy = 3;
		panel_1.add(delMemDetails, gbc_delMemDetails);

		btnDeleteMember = new JButton();
		btnDeleteMember.setFont(new Font("Tahoma", Font.PLAIN, 20));
		btnDeleteMember.setText("Delete Member");
		btnDeleteMember.setEnabled(false);
		btnDeleteMember.addActionListener(new ActionListener() {public void actionPerformed(ActionEvent confirmAE){

			//Do something to delete Member	
			int del = Integer.parseInt(memToDel.getText());
			lDB.deleteMember(del);

			UIManager.put("OptionPane.messageFont", new Font("TimesNewRoman",Font.BOLD,20));
			UIManager.put("OptionPane.buttonFont", new Font("SansSerif",Font.BOLD,20));
			JOptionPane.showMessageDialog(null,"Member_ID: " + del + " deleted.","Member Deleted",JOptionPane.INFORMATION_MESSAGE);

			memToDel.setText("");
			btnDeleteMember.setEnabled(false);

		}});

		confirmDelBtn = new JButton();
		confirmDelBtn.setText("Confirm Member");
		confirmDelBtn.setFont(new Font("Tahoma", Font.PLAIN, 20));

		confirmDelBtn.addActionListener(new ActionListener() {public void actionPerformed(ActionEvent confirmAE){

			int member = Integer.parseInt(memToDel.getText());
			
			String output = lDB.getMemDetails(member);
		
				try{
				String[] finalOutput = output.split("/");
				String name = finalOutput[1] + " " + finalOutput[2] + "\n"; // hh:mm:ss.s
				// Won't use address as it isn't really needed
				//String address = finalOutput[3] + "\n";

				String phone = finalOutput[4] +"\n";
				String dob = finalOutput[5];

				delMemDetails.setText("Name:\n " + name + "Phone#:\n " + phone +"D.O.B:\n "+ dob);
				btnDeleteMember.setEnabled(true);}
				catch(Exception e){
					System.out.println(e.getMessage());
					delMemDetails.setText("");
					btnDeleteMember.setEnabled(false);
				}
			}});




		GridBagConstraints gbc_confirmDelBtn = new GridBagConstraints();
		gbc_confirmDelBtn.insets = new Insets(0, 0, 5, 5);
		gbc_confirmDelBtn.gridx = 2;
		gbc_confirmDelBtn.gridy = 4;
		panel_1.add(confirmDelBtn, gbc_confirmDelBtn);


		GridBagConstraints gbc_btnDeleteMember = new GridBagConstraints();
		gbc_btnDeleteMember.anchor = GridBagConstraints.NORTH;
		gbc_btnDeleteMember.fill = GridBagConstraints.HORIZONTAL;
		gbc_btnDeleteMember.insets = new Insets(0, 0, 5, 5);
		gbc_btnDeleteMember.gridx = 2;
		gbc_btnDeleteMember.gridy = 5;
		panel_1.add(btnDeleteMember, gbc_btnDeleteMember);

		tabbedPane = new JTabbedPane();
		LeisureCentre.addTab("Staff", null, tabbedPane, null);
		tabbedPane.setFont(tabFont);

		adStaffPan = new JPanel();
		tabbedPane.addTab("Add Staff", null, adStaffPan, null);
		GridBagLayout gbl_adStaffPan = new GridBagLayout();
		gbl_adStaffPan.columnWidths = new int[]{21, 97, 165, 43, 0, 52, 0};
		gbl_adStaffPan.rowHeights = new int[]{26, 26, 43, 39, 26, 33, 0, 33, 33, 33, 35, 0};
		gbl_adStaffPan.columnWeights = new double[]{0.0, 0.0, 0.0, 0.0, 0.0, 0.0, Double.MIN_VALUE};
		gbl_adStaffPan.rowWeights = new double[]{0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, Double.MIN_VALUE};
		adStaffPan.setLayout(gbl_adStaffPan);

		lblStaffDetails = new JLabel();
		lblStaffDetails.setText("Staff Details");
		lblStaffDetails.setFont(new Font("Tahoma", Font.BOLD, 22));
		GridBagConstraints gbc_lblStaffDetails = new GridBagConstraints();
		gbc_lblStaffDetails.anchor = GridBagConstraints.NORTHWEST;
		gbc_lblStaffDetails.insets = new Insets(0, 0, 5, 5);
		gbc_lblStaffDetails.gridx = 1;
		gbc_lblStaffDetails.gridy = 1;
		adStaffPan.add(lblStaffDetails, gbc_lblStaffDetails);

		lblPermissionLevel = new JLabel();
		lblPermissionLevel.setText("Permission Level");
		lblPermissionLevel.setFont(new Font("Tahoma", Font.BOLD, 22));
		GridBagConstraints gbc_lblPermissionLevel = new GridBagConstraints();
		gbc_lblPermissionLevel.anchor = GridBagConstraints.SOUTHWEST;
		gbc_lblPermissionLevel.insets = new Insets(0, 0, 5, 5);
		gbc_lblPermissionLevel.gridx = 4;
		gbc_lblPermissionLevel.gridy = 1;
		adStaffPan.add(lblPermissionLevel, gbc_lblPermissionLevel);

		label_12 = new JLabel();
		label_12.setText("First Name");
		label_12.setFont(new Font("Tahoma", Font.PLAIN, 18));
		GridBagConstraints gbc_label_12 = new GridBagConstraints();
		gbc_label_12.fill = GridBagConstraints.HORIZONTAL;
		gbc_label_12.insets = new Insets(0, 0, 5, 5);
		gbc_label_12.gridx = 1;
		gbc_label_12.gridy = 3;
		adStaffPan.add(label_12, gbc_label_12);

		textField_9 = new JTextField();
		textField_9.setFont(new Font("Tahoma", Font.PLAIN, 18));
		GridBagConstraints gbc_textField_9 = new GridBagConstraints();
		gbc_textField_9.fill = GridBagConstraints.HORIZONTAL;
		gbc_textField_9.insets = new Insets(0, 0, 5, 5);
		gbc_textField_9.gridx = 2;
		gbc_textField_9.gridy = 3;
		adStaffPan.add(textField_9, gbc_textField_9);

		comboBox = new JComboBox<String>();
		comboBox.setFont(new Font("Tahoma", Font.PLAIN, 18));
		GridBagConstraints gbc_comboBox = new GridBagConstraints();
		gbc_comboBox.anchor = GridBagConstraints.WEST;
		gbc_comboBox.insets = new Insets(0, 0, 5, 5);
		gbc_comboBox.gridx = 4;
		gbc_comboBox.gridy = 3;
		adStaffPan.add(comboBox, gbc_comboBox);

		label_13 = new JLabel();
		label_13.setText("Surname");
		label_13.setFont(new Font("Tahoma", Font.PLAIN, 18));
		GridBagConstraints gbc_label_13 = new GridBagConstraints();
		gbc_label_13.anchor = GridBagConstraints.WEST;
		gbc_label_13.insets = new Insets(0, 0, 5, 5);
		gbc_label_13.gridx = 1;
		gbc_label_13.gridy = 4;
		adStaffPan.add(label_13, gbc_label_13);

		textField_10 = new JTextField();
		textField_10.setFont(new Font("Tahoma", Font.PLAIN, 18));
		GridBagConstraints gbc_textField_10 = new GridBagConstraints();
		gbc_textField_10.fill = GridBagConstraints.HORIZONTAL;
		gbc_textField_10.insets = new Insets(0, 0, 5, 5);
		gbc_textField_10.gridx = 2;
		gbc_textField_10.gridy = 4;
		adStaffPan.add(textField_10, gbc_textField_10);

		label_14 = new JLabel();
		label_14.setText("Address");
		label_14.setFont(new Font("Tahoma", Font.PLAIN, 18));
		GridBagConstraints gbc_label_14 = new GridBagConstraints();
		gbc_label_14.anchor = GridBagConstraints.WEST;
		gbc_label_14.insets = new Insets(0, 0, 5, 5);
		gbc_label_14.gridx = 1;
		gbc_label_14.gridy = 5;
		adStaffPan.add(label_14, gbc_label_14);

		textField_11 = new JTextField();
		textField_11.setFont(new Font("Tahoma", Font.PLAIN, 18));
		GridBagConstraints gbc_textField_11 = new GridBagConstraints();
		gbc_textField_11.fill = GridBagConstraints.HORIZONTAL;
		gbc_textField_11.insets = new Insets(0, 0, 5, 5);
		gbc_textField_11.gridx = 2;
		gbc_textField_11.gridy = 5;
		adStaffPan.add(textField_11, gbc_textField_11);

		label_15 = new JLabel();
		label_15.setText("Phone #");
		label_15.setFont(new Font("Tahoma", Font.PLAIN, 18));
		GridBagConstraints gbc_label_15 = new GridBagConstraints();
		gbc_label_15.anchor = GridBagConstraints.WEST;
		gbc_label_15.insets = new Insets(0, 0, 5, 5);
		gbc_label_15.gridx = 1;
		gbc_label_15.gridy = 6;
		adStaffPan.add(label_15, gbc_label_15);

		textField_12 = new JTextField();
		textField_12.setFont(new Font("Tahoma", Font.PLAIN, 18));
		GridBagConstraints gbc_textField_12 = new GridBagConstraints();
		gbc_textField_12.fill = GridBagConstraints.HORIZONTAL;
		gbc_textField_12.insets = new Insets(0, 0, 5, 5);
		gbc_textField_12.gridx = 2;
		gbc_textField_12.gridy = 6;
		adStaffPan.add(textField_12, gbc_textField_12);

		label_16 = new JLabel();
		label_16.setText("D.O.B");
		label_16.setFont(new Font("Tahoma", Font.PLAIN, 18));
		GridBagConstraints gbc_label_16 = new GridBagConstraints();
		gbc_label_16.anchor = GridBagConstraints.WEST;
		gbc_label_16.insets = new Insets(0, 0, 5, 5);
		gbc_label_16.gridx = 1;
		gbc_label_16.gridy = 7;
		adStaffPan.add(label_16, gbc_label_16);

		textField_13 = new JTextField();
		textField_13.setText("YYYY-MM-DD");
		textField_13.setFont(new Font("Tahoma", Font.PLAIN, 18));
		GridBagConstraints gbc_textField_13 = new GridBagConstraints();
		gbc_textField_13.fill = GridBagConstraints.HORIZONTAL;
		gbc_textField_13.insets = new Insets(0, 0, 5, 5);
		gbc_textField_13.gridx = 2;
		gbc_textField_13.gridy = 7;
		adStaffPan.add(textField_13, gbc_textField_13);

		btnCreateStaffMember = new JButton();
		btnCreateStaffMember.setText("Create Staff Member");
		btnCreateStaffMember.setFont(new Font("Tahoma", Font.PLAIN, 18));
		GridBagConstraints gbc_btnCreateStaffMember = new GridBagConstraints();
		gbc_btnCreateStaffMember.fill = GridBagConstraints.HORIZONTAL;
		gbc_btnCreateStaffMember.insets = new Insets(0, 0, 5, 5);
		gbc_btnCreateStaffMember.gridx = 4;
		gbc_btnCreateStaffMember.gridy = 7;
		adStaffPan.add(btnCreateStaffMember, gbc_btnCreateStaffMember);

		delStaffPan = new JPanel();
		tabbedPane.addTab("Delete Staff", null, delStaffPan, null);
		GridBagLayout gbl_delStaffPan = new GridBagLayout();
		gbl_delStaffPan.columnWidths = new int[]{21, 97, 165, 43, 0, 52, 0};
		gbl_delStaffPan.rowHeights = new int[]{26, 26, 43, 39, 26, 33, 0, 33, 33, 33, 35, 0};
		gbl_delStaffPan.columnWeights = new double[]{0.0, 0.0, 0.0, 0.0, 0.0, 0.0, Double.MIN_VALUE};
		gbl_delStaffPan.rowWeights = new double[]{0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, Double.MIN_VALUE};
		delStaffPan.setLayout(gbl_delStaffPan);

		lblStaffDetails_1 = new JLabel();
		lblStaffDetails_1.setText("Staff Details");
		lblStaffDetails_1.setFont(new Font("Tahoma", Font.BOLD, 22));
		GridBagConstraints gbc_lblStaffDetails_1 = new GridBagConstraints();
		gbc_lblStaffDetails_1.anchor = GridBagConstraints.NORTHWEST;
		gbc_lblStaffDetails_1.insets = new Insets(0, 0, 5, 5);
		gbc_lblStaffDetails_1.gridx = 1;
		gbc_lblStaffDetails_1.gridy = 1;
		delStaffPan.add(lblStaffDetails_1, gbc_lblStaffDetails_1);

		label_21 = new JLabel();
		label_21.setText("First Name");
		label_21.setFont(new Font("Tahoma", Font.PLAIN, 18));
		GridBagConstraints gbc_label_21 = new GridBagConstraints();
		gbc_label_21.fill = GridBagConstraints.HORIZONTAL;
		gbc_label_21.insets = new Insets(0, 0, 5, 5);
		gbc_label_21.gridx = 1;
		gbc_label_21.gridy = 3;
		delStaffPan.add(label_21, gbc_label_21);

		textField_15 = new JTextField();
		textField_15.setFont(new Font("Tahoma", Font.PLAIN, 18));
		GridBagConstraints gbc_textField_15 = new GridBagConstraints();
		gbc_textField_15.fill = GridBagConstraints.HORIZONTAL;
		gbc_textField_15.insets = new Insets(0, 0, 5, 5);
		gbc_textField_15.gridx = 2;
		gbc_textField_15.gridy = 3;
		delStaffPan.add(textField_15, gbc_textField_15);

		label_22 = new JLabel();
		label_22.setText("Surname");
		label_22.setFont(new Font("Tahoma", Font.PLAIN, 18));
		GridBagConstraints gbc_label_22 = new GridBagConstraints();
		gbc_label_22.anchor = GridBagConstraints.WEST;
		gbc_label_22.insets = new Insets(0, 0, 5, 5);
		gbc_label_22.gridx = 1;
		gbc_label_22.gridy = 4;
		delStaffPan.add(label_22, gbc_label_22);

		textField_16 = new JTextField();
		textField_16.setFont(new Font("Tahoma", Font.PLAIN, 18));
		GridBagConstraints gbc_textField_16 = new GridBagConstraints();
		gbc_textField_16.fill = GridBagConstraints.HORIZONTAL;
		gbc_textField_16.insets = new Insets(0, 0, 5, 5);
		gbc_textField_16.gridx = 2;
		gbc_textField_16.gridy = 4;
		delStaffPan.add(textField_16, gbc_textField_16);

		label_23 = new JLabel();
		label_23.setText("Address");
		label_23.setFont(new Font("Tahoma", Font.PLAIN, 18));
		GridBagConstraints gbc_label_23 = new GridBagConstraints();
		gbc_label_23.anchor = GridBagConstraints.WEST;
		gbc_label_23.insets = new Insets(0, 0, 5, 5);
		gbc_label_23.gridx = 1;
		gbc_label_23.gridy = 5;
		delStaffPan.add(label_23, gbc_label_23);

		textField_17 = new JTextField();
		textField_17.setFont(new Font("Tahoma", Font.PLAIN, 18));
		GridBagConstraints gbc_textField_17 = new GridBagConstraints();
		gbc_textField_17.fill = GridBagConstraints.HORIZONTAL;
		gbc_textField_17.insets = new Insets(0, 0, 5, 5);
		gbc_textField_17.gridx = 2;
		gbc_textField_17.gridy = 5;
		delStaffPan.add(textField_17, gbc_textField_17);

		label_24 = new JLabel();
		label_24.setText("Phone #");
		label_24.setFont(new Font("Tahoma", Font.PLAIN, 18));
		GridBagConstraints gbc_label_24 = new GridBagConstraints();
		gbc_label_24.anchor = GridBagConstraints.WEST;
		gbc_label_24.insets = new Insets(0, 0, 5, 5);
		gbc_label_24.gridx = 1;
		gbc_label_24.gridy = 6;
		delStaffPan.add(label_24, gbc_label_24);

		textField_18 = new JTextField();
		textField_18.setFont(new Font("Tahoma", Font.PLAIN, 18));
		GridBagConstraints gbc_textField_18 = new GridBagConstraints();
		gbc_textField_18.fill = GridBagConstraints.HORIZONTAL;
		gbc_textField_18.insets = new Insets(0, 0, 5, 5);
		gbc_textField_18.gridx = 2;
		gbc_textField_18.gridy = 6;
		delStaffPan.add(textField_18, gbc_textField_18);

		label_25 = new JLabel();
		label_25.setText("D.O.B");
		label_25.setFont(new Font("Tahoma", Font.PLAIN, 18));
		GridBagConstraints gbc_label_25 = new GridBagConstraints();
		gbc_label_25.anchor = GridBagConstraints.WEST;
		gbc_label_25.insets = new Insets(0, 0, 5, 5);
		gbc_label_25.gridx = 1;
		gbc_label_25.gridy = 7;
		delStaffPan.add(label_25, gbc_label_25);

		textField_19 = new JTextField();
		textField_19.setText("YYYY-MM-DD");
		textField_19.setFont(new Font("Tahoma", Font.PLAIN, 18));
		GridBagConstraints gbc_textField_19 = new GridBagConstraints();
		gbc_textField_19.fill = GridBagConstraints.HORIZONTAL;
		gbc_textField_19.insets = new Insets(0, 0, 5, 5);
		gbc_textField_19.gridx = 2;
		gbc_textField_19.gridy = 7;
		delStaffPan.add(textField_19, gbc_textField_19);

		btnConfirmDelete = new JButton();
		btnConfirmDelete.setText("Confirm Delete");
		btnConfirmDelete.setFont(new Font("Tahoma", Font.PLAIN, 18));
		GridBagConstraints gbc_btnConfirmDelete = new GridBagConstraints();
		gbc_btnConfirmDelete.fill = GridBagConstraints.HORIZONTAL;
		gbc_btnConfirmDelete.insets = new Insets(0, 0, 5, 5);
		gbc_btnConfirmDelete.gridx = 4;
		gbc_btnConfirmDelete.gridy = 7;
		delStaffPan.add(btnConfirmDelete, gbc_btnConfirmDelete);

		upStaffPan = new JPanel();
		tabbedPane.addTab("Update Staff Privileges", null, upStaffPan, null);
		GridBagLayout gbl_upStaffPan = new GridBagLayout();
		gbl_upStaffPan.columnWidths = new int[]{21, 97, 165, 43, 0, 52, 0};
		gbl_upStaffPan.rowHeights = new int[]{26, 26, 43, 39, 26, 33, 0, 33, 33, 33, 35, 0};
		gbl_upStaffPan.columnWeights = new double[]{0.0, 0.0, 0.0, 0.0, 0.0, 0.0, Double.MIN_VALUE};
		gbl_upStaffPan.rowWeights = new double[]{0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, Double.MIN_VALUE};
		upStaffPan.setLayout(gbl_upStaffPan);

		lblStaffDetails_2 = new JLabel();
		lblStaffDetails_2.setText("Staff Details");
		lblStaffDetails_2.setFont(new Font("Tahoma", Font.BOLD, 22));
		GridBagConstraints gbc_lblStaffDetails_2 = new GridBagConstraints();
		gbc_lblStaffDetails_2.anchor = GridBagConstraints.NORTHWEST;
		gbc_lblStaffDetails_2.insets = new Insets(0, 0, 5, 5);
		gbc_lblStaffDetails_2.gridx = 1;
		gbc_lblStaffDetails_2.gridy = 1;
		upStaffPan.add(lblStaffDetails_2, gbc_lblStaffDetails_2);

		lblPermissionLevel_1 = new JLabel();
		lblPermissionLevel_1.setText("Permission Level");
		lblPermissionLevel_1.setFont(new Font("Tahoma", Font.BOLD, 22));
		GridBagConstraints gbc_lblPermissionLevel_1 = new GridBagConstraints();
		gbc_lblPermissionLevel_1.anchor = GridBagConstraints.SOUTHWEST;
		gbc_lblPermissionLevel_1.insets = new Insets(0, 0, 5, 5);
		gbc_lblPermissionLevel_1.gridx = 4;
		gbc_lblPermissionLevel_1.gridy = 1;
		upStaffPan.add(lblPermissionLevel_1, gbc_lblPermissionLevel_1);

		lblStaffId_1 = new JLabel();
		lblStaffId_1.setText("Staff ID");
		lblStaffId_1.setFont(new Font("Tahoma", Font.PLAIN, 18));
		GridBagConstraints gbc_lblStaffId_1 = new GridBagConstraints();
		gbc_lblStaffId_1.fill = GridBagConstraints.HORIZONTAL;
		gbc_lblStaffId_1.insets = new Insets(0, 0, 5, 5);
		gbc_lblStaffId_1.gridx = 1;
		gbc_lblStaffId_1.gridy = 3;
		upStaffPan.add(lblStaffId_1, gbc_lblStaffId_1);

		textField_21 = new JTextField();
		textField_21.setFont(new Font("Tahoma", Font.PLAIN, 18));
		GridBagConstraints gbc_textField_21 = new GridBagConstraints();
		gbc_textField_21.fill = GridBagConstraints.HORIZONTAL;
		gbc_textField_21.insets = new Insets(0, 0, 5, 5);
		gbc_textField_21.gridx = 2;
		gbc_textField_21.gridy = 3;
		upStaffPan.add(textField_21, gbc_textField_21);

		comboBox_2 = new JComboBox<String>();
		comboBox_2.setFont(new Font("Tahoma", Font.PLAIN, 18));
		GridBagConstraints gbc_comboBox_2 = new GridBagConstraints();
		gbc_comboBox_2.anchor = GridBagConstraints.WEST;
		gbc_comboBox_2.insets = new Insets(0, 0, 5, 5);
		gbc_comboBox_2.gridx = 4;
		gbc_comboBox_2.gridy = 3;
		upStaffPan.add(comboBox_2, gbc_comboBox_2);
		
				btnConfirmUpdate = new JButton();
				btnConfirmUpdate.setText("Confirm Update");
				btnConfirmUpdate.setFont(new Font("Tahoma", Font.PLAIN, 18));
				GridBagConstraints gbc_btnConfirmUpdate = new GridBagConstraints();
				gbc_btnConfirmUpdate.fill = GridBagConstraints.HORIZONTAL;
				gbc_btnConfirmUpdate.insets = new Insets(0, 0, 5, 5);
				gbc_btnConfirmUpdate.gridx = 1;
				gbc_btnConfirmUpdate.gridy = 4;
				upStaffPan.add(btnConfirmUpdate, gbc_btnConfirmUpdate);

		int mem = LeisureCentre.indexOfTab("Membership");
		int sta = LeisureCentre.indexOfTab("Staff");

		LeisureCentre.setEnabledAt(mem,false);
		LeisureCentre.setEnabledAt(sta,false);
		GridBagConstraints gbc_LeisureCentre = new GridBagConstraints();
		gbc_LeisureCentre.anchor = GridBagConstraints.NORTHWEST;
		gbc_LeisureCentre.gridx = 0;
		gbc_LeisureCentre.gridy = 0;
		getContentPane().add(LeisureCentre, gbc_LeisureCentre);

		btnConfirmLogin.addActionListener(new ActionListener() {public void actionPerformed(ActionEvent confirmAE){

			int l1 = Integer.parseInt(loginID.getText());	

			if(lDB.getPassword(l1, loginPassword.getText())){

				LeisureCentre.setEnabledAt(mem,true);
				LeisureCentre.setEnabledAt(sta,true);
			}
			else{

				//jTabbedPane3.setEnabled(false);
				UIManager.put("OptionPane.messageFont", new Font("TimesNewRoman",Font.BOLD,20));
				UIManager.put("OptionPane.buttonFont", new Font("SansSerif",Font.BOLD,20));
				JOptionPane.showMessageDialog(null,"Failure","Please Try Again",JOptionPane.INFORMATION_MESSAGE);
			}


		}});

		
		scheduleBtn.addActionListener(new ActionListener() {@SuppressWarnings("deprecation")
		public void actionPerformed(ActionEvent confirmAE){

			//yyyy-mm-dd

			//1900
			//1

			try{

				
				
				int year,month,day;
				String sDay,sMonth,sFinalDate = null;
				day = dateChooser_1.getDate().getDate();
				month = dateChooser_1.getDate().getMonth() + 1;
				year = dateChooser_1.getDate().getYear() + 1900;


				if(day < 10){
					sDay = "0" + day;
				}
				else{
					sDay = Integer.toString(day);
				}
				if(month < 10){
					sMonth = "0" + month;
				}
				else{
					sMonth = Integer.toString(month);
				}

				sFinalDate = year + "-" + sMonth + "-" + sDay;	
				
				label_35.setText("Schedule for: " + sFinalDate);
				
				table_2 = lDB.makeScheduleTable(sFinalDate);
				scrollPane_1.setViewportView(table_2);
				
				
			
			}
			catch(Exception e){
				System.out.println(e.getMessage());
				UIManager.put("OptionPane.messageFont", new Font("TimesNewRoman",Font.BOLD,20));
				UIManager.put("OptionPane.buttonFont", new Font("SansSerif",Font.BOLD,20));
				JOptionPane.showMessageDialog(null,"NO DATE SELECTED!","Please Try Again",JOptionPane.WARNING_MESSAGE);
			}
			finally{

			}

		}} );




		LeisureCentre.getAccessibleContext().setAccessibleName("Booking");

		pack();
		setResizable(false);
	}// </editor-fold>//GEN-END:initComponents

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_jButton2ActionPerformed

	private void jComboBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox7ActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_jComboBox7ActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(leisureCentreProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(leisureCentreProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(leisureCentreProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(leisureCentreProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				leisureCentreProject p;
				try {
					p = new leisureCentreProject();
					p.setVisible(true);
					p.pack();
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}

				//p.setResizable(false);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JTabbedPane LeisureCentre;
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JComboBox<String> jComboBox1;
	private javax.swing.JComboBox<String> jComboBox7;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JTabbedPane jTabbedPane1;
	private javax.swing.JTabbedPane jTabbedPane3;
	private javax.swing.JTabbedPane jTabbedPane6;
	private javax.swing.JTextField addMemFiNa;
	private javax.swing.JTextField addMemLaNa;
	private javax.swing.JTextField addMemAd;
	private javax.swing.JTextField addMemPhone;
	private javax.swing.JTextField addMemDOB;
	private JPanel panel;
	private JLabel label;
	private JLabel lblPhone;
	private JLabel label_2;
	private JLabel label_3;
	private JLabel label_4;
	private JLabel label_7;
	private JLabel label_8;
	private JTextField textField;
	private JTextField textField_2;
	private JTextField textField_3;
	private JTextField textField_4;
	private JTextField textField_5;
	private JTextField textField_6;
	private JLabel label_9;
	private JButton button;
	private JLabel lblNewLabel;
	private JTable table_1;
	private JPanel panel_1;
	private JLabel lblMemberToDelete;
	private JLabel lblMemberId;
	private JTextField memToDel;
	private JButton btnDeleteMember;
	private JTabbedPane tabbedPane;
	private JTable table_2;
	private JTextField loginID;
	private JTextField loginPassword;
	private JPanel adStaffPan;
	private JLabel lblStaffDetails;
	private JLabel lblPermissionLevel;
	private JLabel label_12;
	private JTextField textField_9;
	private JComboBox<String> comboBox;
	private JLabel label_13;
	private JTextField textField_10;
	private JLabel label_14;
	private JTextField textField_11;
	private JLabel label_15;
	private JTextField textField_12;
	private JLabel label_16;
	private JTextField textField_13;
	private JButton btnCreateStaffMember;
	private JPanel delStaffPan;
	private JLabel lblStaffDetails_1;
	private JLabel label_21;
	private JTextField textField_15;
	private JLabel label_22;
	private JTextField textField_16;
	private JLabel label_23;
	private JTextField textField_17;
	private JLabel label_24;
	private JTextField textField_18;
	private JLabel label_25;
	private JTextField textField_19;
	private JButton btnConfirmDelete;
	private JPanel upStaffPan;
	private JLabel lblStaffDetails_2;
	private JLabel lblPermissionLevel_1;
	private JLabel lblStaffId_1;
	private JTextField textField_21;
	private JComboBox<String> comboBox_2;
	private JButton btnConfirmUpdate;
	private JLabel lblMembershipTypeid;
	private JTextField memShip;
	private JTextArea delMemDetails;
	private JButton confirmDelBtn;
	private JScrollPane scrollPane_1;
}